//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanSweep2_CLI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanSweep2_CLI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;1MB recovered from removing Windows Error Reports..
        /// </summary>
        internal static string _1MB_recovered_from_removing_Windows_Error_Reports {
            get {
                return ResourceManager.GetString("_1MB_recovered_from_removing_Windows_Error_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;1MB recovered from Temporary Files..
        /// </summary>
        internal static string _1MB_recovered_from_Temporary_Files {
            get {
                return ResourceManager.GetString("1MB_recovered_from_Temporary_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;1MB recovered from Temporary Internet Files..
        /// </summary>
        internal static string _1MB_recovered_from_Temporary_Internet_Files {
            get {
                return ResourceManager.GetString("_1MB_recovered_from_Temporary_Internet_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;1MB recovered from Temporary Setup Files..
        /// </summary>
        internal static string _1MB_recovered_from_Temporary_Setup_Files {
            get {
                return ResourceManager.GetString("_1MB_recovered_from_Temporary_Setup_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;1MB recovered from Windows Delivery Optimization Files..
        /// </summary>
        internal static string _1MB_recovered_from_Windows_Delivery_Optimization_Files {
            get {
                return ResourceManager.GetString("_1MB_recovered_from_Windows_Delivery_Optimization_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;1MB recovered from Windows Update Logs..
        /// </summary>
        internal static string _1MB_recovered_from_Windows_Update_Logs {
            get {
                return ResourceManager.GetString("_1MB_recovered_from_Windows_Update_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of CleanSweep2_CLI is available!.
        /// </summary>
        internal static string A_new_version_of_CleanSweep2_CLI_is_available {
            get {
                return ResourceManager.GetString("A_new_version_of_CleanSweep2_CLI_is_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  appears to be in use or locked. Skipping....
        /// </summary>
        internal static string appears_to_be_in_use_or_locked__Skipping {
            get {
                return ResourceManager.GetString("appears_to_be_in_use_or_locked__Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to remove all file history snapshots except latest.
        /// </summary>
        internal static string Attempting_to_remove_all_file_history_snapshots_except_latest {
            get {
                return ResourceManager.GetString("Attempting_to_remove_all_file_history_snapshots_except_latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorical breakdown:.
        /// </summary>
        internal static string Categorical_breakdown {
            get {
                return ResourceManager.GetString("Categorical_breakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome cache was cleared..
        /// </summary>
        internal static string Chrome_cache_was_cleared {
            get {
                return ResourceManager.GetString("Chrome_cache_was_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome Data Size: .
        /// </summary>
        internal static string Chrome_Data_Size {
            get {
                return ResourceManager.GetString("Chrome_Data_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CleanSweep v2.2.0.
        /// </summary>
        internal static string CleanSweep {
            get {
                return ResourceManager.GetString("CleanSweep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CleanSweep is, and will always be free, but beer is not!.
        /// </summary>
        internal static string CleanSweep_is__and_will_always_be_free__but_beer_is_not {
            get {
                return ResourceManager.GetString("CleanSweep_is__and_will_always_be_free__but_beer_is_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared Thumbnail Cache!.
        /// </summary>
        internal static string Cleared_Thumbnail_Cache {
            get {
                return ResourceManager.GetString("Cleared_Thumbnail_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing Thumbnail Cache.
        /// </summary>
        internal static string Clearing_Thumbnail_Cache {
            get {
                return ResourceManager.GetString("Clearing_Thumbnail_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string Colon_Symbol {
            get {
                return ResourceManager.GetString("Colon_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t delete .
        /// </summary>
        internal static string Couldn_t_delete {
            get {
                return ResourceManager.GetString("Couldn_t_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t remove .
        /// </summary>
        internal static string Couldn_t_remove {
            get {
                return ResourceManager.GetString("Couldn_t_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Thomas Loupe..
        /// </summary>
        internal static string Created_by_Thomas_Loupe {
            get {
                return ResourceManager.GetString("Created_by_Thomas_Loupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version: v2.2.0.
        /// </summary>
        internal static string Current_version {
            get {
                return ResourceManager.GetString("Current_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted: .
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Windows Defender Log Files....
        /// </summary>
        internal static string Deleting_Windows_Defender_Log_Files {
            get {
                return ResourceManager.GetString("Deleting_Windows_Defender_Log_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory already removed: .
        /// </summary>
        internal static string Directory_already_removed {
            get {
                return ResourceManager.GetString("Directory_already_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge cache was cleared..
        /// </summary>
        internal static string Edge_cache_was_cleared {
            get {
                return ResourceManager.GetString("Edge_cache_was_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge Data Size: .
        /// </summary>
        internal static string Edge_Data_Size {
            get {
                return ResourceManager.GetString("Edge_Data_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emptied Recycle Bin!.
        /// </summary>
        internal static string Emptied_Recycle_Bin {
            get {
                return ResourceManager.GetString("Emptied_Recycle_Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emptying Recycle Bin.
        /// </summary>
        internal static string Emptying_Recycle_Bin {
            get {
                return ResourceManager.GetString("Emptying_Recycle_Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending any Chrome processes....
        /// </summary>
        internal static string Ending_any_Chrome_processes {
            get {
                return ResourceManager.GetString("Ending_any_Chrome_processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending any Edge processes....
        /// </summary>
        internal static string Ending_any_Edge_processes {
            get {
                return ResourceManager.GetString("Ending_any_Edge_processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Logs were cleared..
        /// </summary>
        internal static string Event_Logs_were_cleared {
            get {
                return ResourceManager.GetString("Event_Logs_were_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [o].
        /// </summary>
        internal static string Folder_o {
            get {
                return ResourceManager.GetString("Folder_o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [x].
        /// </summary>
        internal static string Folder_x {
            get {
                return ResourceManager.GetString("Folder_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Windows Installer Cache. Cleaning....
        /// </summary>
        internal static string Found_Windows_Installer_Cache__Cleaning {
            get {
                return ResourceManager.GetString("Found_Windows_Installer_Cache__Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Windows.old directory. Cleaning....
        /// </summary>
        internal static string Found_Windows_old_directory__Cleaning {
            get {
                return ResourceManager.GetString("Found_Windows_old_directory__Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github: https://github.com/thomasloupe.
        /// </summary>
        internal static string Github__https___github_com_thomasloupe {
            get {
                return ResourceManager.GetString("Github__https___github_com_thomasloupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If file history was enabled, all versions except latest were removed..
        /// </summary>
        internal static string If_file_history_was_enabled__all_versions_except_latest_were_removed {
            get {
                return ResourceManager.GetString("If_file_history_was_enabled__all_versions_except_latest_were_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;d like to buy me a beer anyway, I won&apos;t tell you not to..
        /// </summary>
        internal static string If_you_d_like_to_buy_me_a_beer_anyway__I_won_t_tell_you_not_to {
            get {
                return ResourceManager.GetString("If_you_d_like_to_buy_me_a_beer_anyway__I_won_t_tell_you_not_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version: .
        /// </summary>
        internal static string Latest_version {
            get {
                return ResourceManager.GetString("Latest_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------------------------------.
        /// </summary>
        internal static string LineSeparator {
            get {
                return ResourceManager.GetString("LineSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB from removing MSO Cache..
        /// </summary>
        internal static string MB_from_removing_MSO_Cache {
            get {
                return ResourceManager.GetString("MB_from_removing_MSO_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB from removing Temporary Files..
        /// </summary>
        internal static string MB_from_removing_Temporary_Files_ {
            get {
                return ResourceManager.GetString("MB_from_removing_Temporary_Files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB from removing Temporary Internet Files..
        /// </summary>
        internal static string MB_from_removing_Temporary_Internet_Files_ {
            get {
                return ResourceManager.GetString("MB_from_removing_Temporary_Internet_Files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB from removing Temporary Setup Files..
        /// </summary>
        internal static string MB_from_removing_Temporary_Setup_Files {
            get {
                return ResourceManager.GetString("MB_from_removing_Temporary_Setup_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB from removing Windows Delivery Optimization Files..
        /// </summary>
        internal static string MB_from_removing_Windows_Delivery_Optimization_Files_ {
            get {
                return ResourceManager.GetString("MB_from_removing_Windows_Delivery_Optimization_Files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB from removing Windows Error Reports..
        /// </summary>
        internal static string MB_from_removing_Windows_Error_Reports {
            get {
                return ResourceManager.GetString("MB_from_removing_Windows_Error_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB from removing Windows Installer Cache..
        /// </summary>
        internal static string MB_from_removing_Windows_Installer_Cache {
            get {
                return ResourceManager.GetString("MB_from_removing_Windows_Installer_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB from removing Windows Update Logs..
        /// </summary>
        internal static string MB_from_removing_Windows_Update_Logs {
            get {
                return ResourceManager.GetString("MB_from_removing_Windows_Update_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSO Cache size: .
        /// </summary>
        internal static string MSO_Cache_size {
            get {
                return ResourceManager.GetString("MSO_Cache_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arguments given. Please re-run CleanSweep2_CLI with arguments..
        /// </summary>
        internal static string No_Arguments_Given {
            get {
                return ResourceManager.GetString("No_Arguments_Given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Delivery Optimization Files needed to be cleaned..
        /// </summary>
        internal static string No_Delivery_Optimization_Files_needed_to_be_cleaned {
            get {
                return ResourceManager.GetString("No_Delivery_Optimization_Files_needed_to_be_cleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MSOCache directory found. Skipping....
        /// </summary>
        internal static string No_MSOCache_directory_found__Skipping {
            get {
                return ResourceManager.GetString("No_MSOCache_directory_found__Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Windows.old directory found. Skipping....
        /// </summary>
        internal static string No_Windows_old_directory_found__Skipping {
            get {
                return ResourceManager.GetString("No_Windows_old_directory_found__Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Windows Update Logs directory found. Skipping....
        /// </summary>
        internal static string No_Windows_Update_Logs_directory_found__Skipping {
            get {
                return ResourceManager.GetString("No_Windows_Update_Logs_directory_found__Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        internal static string o {
            get {
                return ResourceManager.GetString("o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old versions of Windows were removed..
        /// </summary>
        internal static string Old_versions_of_Windows_were_removed {
            get {
                return ResourceManager.GetString("Old_versions_of_Windows_were_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential space to reclaim: .
        /// </summary>
        internal static string Potential_space_to_reclaim {
            get {
                return ResourceManager.GetString("Potential_space_to_reclaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovered .
        /// </summary>
        internal static string Recovered {
            get {
                return ResourceManager.GetString("Recovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery results:.
        /// </summary>
        internal static string Recovery_results {
            get {
                return ResourceManager.GetString("Recovery_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle Bin was emptied..
        /// </summary>
        internal static string Recycle_Bin_was_emptied {
            get {
                return ResourceManager.GetString("Recycle_Bin_was_emptied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed .
        /// </summary>
        internal static string Removed {
            get {
                return ResourceManager.GetString("Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept Delivery Optimization Files!.
        /// </summary>
        internal static string Removed_Delivery_Optimization_Files {
            get {
                return ResourceManager.GetString("Removed_Delivery_Optimization_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept file history older than latest snapshot..
        /// </summary>
        internal static string Removed_file_history_older_than_latest_snapshot {
            get {
                return ResourceManager.GetString("Removed_file_history_older_than_latest_snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept Windows Defender Logs!.
        /// </summary>
        internal static string Removed_Windows_Defender_Logs {
            get {
                return ResourceManager.GetString("Removed_Windows_Defender_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweeping old versions of Windows....
        /// </summary>
        internal static string Removing_old_versions_of_Windows {
            get {
                return ResourceManager.GetString("Removing_old_versions_of_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweeping Windows Installer Cache....
        /// </summary>
        internal static string Removing_Windows_Installer_Cache {
            get {
                return ResourceManager.GetString("Removing_Windows_Installer_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarted Explorer.exe process..
        /// </summary>
        internal static string Restarted_Explorer_exe_process {
            get {
                return ResourceManager.GetString("Restarted_Explorer_exe_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down Explorer.exe process....
        /// </summary>
        internal static string Shutting_down_Explorer_exe_process {
            get {
                return ResourceManager.GetString("Shutting_down_Explorer_exe_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Skipping....
        /// </summary>
        internal static string Skipping {
            get {
                return ResourceManager.GetString("Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping....
        /// </summary>
        internal static string Skipping___ {
            get {
                return ResourceManager.GetString("Skipping___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped Chrome processes..
        /// </summary>
        internal static string Stopped_Chrome_processes {
            get {
                return ResourceManager.GetString("Stopped_Chrome_processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped Edge processes..
        /// </summary>
        internal static string Stopped_Edge_processes {
            get {
                return ResourceManager.GetString("Stopped_Edge_processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweeping Chrome cache....
        /// </summary>
        internal static string Sweeping_Chrome_cache {
            get {
                return ResourceManager.GetString("Sweeping_Chrome_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweeping Delivery Optimization Files....
        /// </summary>
        internal static string Sweeping_Delivery_Optimization_Files {
            get {
                return ResourceManager.GetString("Sweeping_Delivery_Optimization_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweeping Edge cache....
        /// </summary>
        internal static string Sweeping_Edge_cache {
            get {
                return ResourceManager.GetString("Sweeping_Edge_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweeping Event Viewer Logs.
        /// </summary>
        internal static string Sweeping_Event_Viewer_Logs {
            get {
                return ResourceManager.GetString("Sweeping_Event_Viewer_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweeping MSO cache....
        /// </summary>
        internal static string Sweeping_MSO_cache {
            get {
                return ResourceManager.GetString("Sweeping_MSO_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweeping Temporary Files...
        ///.
        /// </summary>
        internal static string Sweeping_Temporary_Files {
            get {
                return ResourceManager.GetString("Sweeping_Temporary_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweeping Temporary Internet Files....
        /// </summary>
        internal static string Sweeping_Temporary_Internet_Files {
            get {
                return ResourceManager.GetString("Sweeping_Temporary_Internet_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweeping Temporary Setup Files....
        /// </summary>
        internal static string Sweeping_Temporary_Setup_Files {
            get {
                return ResourceManager.GetString("Sweeping_Temporary_Setup_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweeping Windows Error Reports....
        /// </summary>
        internal static string Sweeping_Windows_Error_Reports {
            get {
                return ResourceManager.GetString("Sweeping_Windows_Error_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweeping Windows Update Logs....
        /// </summary>
        internal static string Sweeping_Windows_Update_Logs {
            get {
                return ResourceManager.GetString("Sweeping_Windows_Update_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept Chrome cache!.
        /// </summary>
        internal static string Swept_Chrome_cache {
            get {
                return ResourceManager.GetString("Swept_Chrome_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept Edge cache!.
        /// </summary>
        internal static string Swept_Edge_cache {
            get {
                return ResourceManager.GetString("Swept_Edge_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept Event Viewer Logs!.
        /// </summary>
        internal static string Swept_Event_Viewer_Logs {
            get {
                return ResourceManager.GetString("Swept_Event_Viewer_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept MSO Cache!.
        /// </summary>
        internal static string Swept_MSO_Cache {
            get {
                return ResourceManager.GetString("Swept_MSO_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept Temporary Files!.
        /// </summary>
        internal static string Swept_Temporary_Files {
            get {
                return ResourceManager.GetString("Swept_Temporary_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept Temporary Internet Files!.
        /// </summary>
        internal static string Swept_Temporary_Internet_Files {
            get {
                return ResourceManager.GetString("Swept_Temporary_Internet_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept Temporary Setup Files!.
        /// </summary>
        internal static string Swept_Temporary_Setup_Files {
            get {
                return ResourceManager.GetString("Swept_Temporary_Setup_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept Windows Error Reports!.
        /// </summary>
        internal static string Swept_Windows_Error_Reports {
            get {
                return ResourceManager.GetString("Swept_Windows_Error_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept Windows Installer Cache!.
        /// </summary>
        internal static string Swept_Windows_Installer_Cache {
            get {
                return ResourceManager.GetString("Swept_Windows_Installer_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept Windows.old directory!.
        /// </summary>
        internal static string Swept_Windows_old_directory {
            get {
                return ResourceManager.GetString("Swept_Windows_old_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept Windows Update Logs!.
        /// </summary>
        internal static string Swept_Windows_Update_Logs {
            get {
                return ResourceManager.GetString("Swept_Windows_Update_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Directory size: .
        /// </summary>
        internal static string Temporary_Directory_size {
            get {
                return ResourceManager.GetString("Temporary_Directory_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Internet Files directory size: .
        /// </summary>
        internal static string Temporary_Internet_Files_directory_size {
            get {
                return ResourceManager.GetString("Temporary_Internet_Files_directory_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Setup Files directory size: .
        /// </summary>
        internal static string Temporary_Setup_Files_directory_size {
            get {
                return ResourceManager.GetString("Temporary_Setup_Files_directory_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail cache was cleared..
        /// </summary>
        internal static string Thumbnail_cache_was_cleared {
            get {
                return ResourceManager.GetString("Thumbnail_cache_was_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total space recovered: .
        /// </summary>
        internal static string Total_space_recovered {
            get {
                return ResourceManager.GetString("Total_space_recovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total space recovered: &lt;1MB.
        /// </summary>
        internal static string Total_space_recovered___1MB {
            get {
                return ResourceManager.GetString("Total_space_recovered___1MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter: https://twitter.com/acid_rain.
        /// </summary>
        internal static string Twitter__https___twitter_com_acid_rain {
            get {
                return ResourceManager.GetString("Twitter__https___twitter_com_acid_rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit https://github.com/thomasloupe/CleanSweep2 to download the latest version..
        /// </summary>
        internal static string Visit_https___github_com_thomasloupe_CleanSweep2_to_download_the_latest_version {
            get {
                return ResourceManager.GetString("Visit_https___github_com_thomasloupe_CleanSweep2_to_download_the_latest_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit https://paypal.me/thomasloupe if you&apos;d like to donate..
        /// </summary>
        internal static string Visit_https___paypal_me_thomasloupe_if_you_d_like_to_donate {
            get {
                return ResourceManager.GetString("Visit_https___paypal_me_thomasloupe_if_you_d_like_to_donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website: https://thomasloupe.com.
        /// </summary>
        internal static string Website__https___thomasloupe_com {
            get {
                return ResourceManager.GetString("Website__https___thomasloupe_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Defender Logs were removed..
        /// </summary>
        internal static string Windows_Defender_Logs_were_removed {
            get {
                return ResourceManager.GetString("Windows_Defender_Logs_were_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Delivery Optimization File size: .
        /// </summary>
        internal static string Windows_Delivery_Optimization_File_size {
            get {
                return ResourceManager.GetString("Windows_Delivery_Optimization_File_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Error Report directory already removed. Skipping.
        /// </summary>
        internal static string Windows_Error_Report_directory_already_removed__Skipping {
            get {
                return ResourceManager.GetString("Windows_Error_Report_directory_already_removed__Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Error Reports size: .
        /// </summary>
        internal static string Windows_Error_Reports_size {
            get {
                return ResourceManager.GetString("Windows_Error_Reports_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Installer Cache size: .
        /// </summary>
        internal static string Windows_Installer_Cache_size {
            get {
                return ResourceManager.GetString("Windows_Installer_Cache_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Update Logs size: .
        /// </summary>
        internal static string Windows_Update_Logs_size {
            get {
                return ResourceManager.GetString("Windows_Update_Logs_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        internal static string x {
            get {
                return ResourceManager.GetString("x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version, {0}!.
        /// </summary>
        internal static string You_have_the_latest_version___0__ {
            get {
                return ResourceManager.GetString("You_have_the_latest_version___0__", resourceCulture);
            }
        }
    }
}
