//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanSweep2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanSweep2.Properties.es", typeof(es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;1MB recuperado de la eliminación de informes de error de Windows....
        /// </summary>
        internal static string _1MB_From_Removing_Windows_Error_Reports_ {
            get {
                return ResourceManager.GetString("<1MB_From_Removing_Windows_Error_Reports_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;1MB recuperado de archivos temporales....
        /// </summary>
        internal static string _1MB_Recovered_From_Temporary_Files {
            get {
                return ResourceManager.GetString("<1MB_Recovered_From_Temporary_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;1MB recuperado de archivos temporales de Internet....
        /// </summary>
        internal static string _1MB_Recovered_From_Temporary_Internet_Files {
            get {
                return ResourceManager.GetString("<1MB_Recovered_From_Temporary_Internet_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;1MB recuperado de archivos de configuración temporal....
        /// </summary>
        internal static string _1MB_Recovered_From_Temporary_Setup_Files {
            get {
                return ResourceManager.GetString("<1MB_Recovered_From_Temporary_Setup_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;1MB recuperado de los archivos de optimización de entrega de Windows....
        /// </summary>
        internal static string _1MB_Recovered_From_Windows_Delivery_Optimization_Files {
            get {
                return ResourceManager.GetString("<1MB_Recovered_From_Windows_Delivery_Optimization_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;1MB recovered from Windows Update Logs....
        /// </summary>
        internal static string _1MB_Recovered_From_Windows_Update_Logs {
            get {
                return ResourceManager.GetString("<1MB_Recovered_From_Windows_Update_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Hay disponible una nueva versión de CleanSweep!
        ///Versión actual: 
        ///Ultima versión: .
        /// </summary>
        internal static string A_new_version_of_CleanSweep_is_available {
            get {
                return ResourceManager.GetString("A_new_version_of_CleanSweep_is_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  parece estar en uso o bloqueado. Salto a la comba....
        /// </summary>
        internal static string appears_to_be_in_use_or_locked__Skipping {
            get {
                return ResourceManager.GetString("appears_to_be_in_use_or_locked__Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intentando eliminar todas las instantáneas del historial de archivos excepto la última.
        /// </summary>
        internal static string Attempting_to_remove_all_file_history_snapshots_except_latest {
            get {
                return ResourceManager.GetString("Attempting_to_remove_all_file_history_snapshots_except_latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desglose categórico:.
        /// </summary>
        internal static string Categorical_breakdown {
            get {
                return ResourceManager.GetString("Categorical_breakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Se borró la caché de Chrome..
        /// </summary>
        internal static string Chome_Cache_Was_Cleared {
            get {
                return ResourceManager.GetString("Chome_Cache_Was_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño de datos de Chrome: .
        /// </summary>
        internal static string Chrome_Data_Size {
            get {
                return ResourceManager.GetString("Chrome_Data_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CleanSweep es gratis, ¡pero la cerveza no!.
        /// </summary>
        internal static string CleanSweep_is_free__but_beer_is_not {
            get {
                return ResourceManager.GetString("CleanSweep_is_free__but_beer_is_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡CleanSweep siempre será gratis!
        ///Si quieres comprarme una cerveza de todos modos, ¡no te diré que no!
        ///¿Le gustaría abrir la página de donaciones ahora?.
        /// </summary>
        internal static string CleanSweep_will_always_be_free {
            get {
                return ResourceManager.GetString("CleanSweep_will_always_be_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar la caché de miniaturas.
        /// </summary>
        internal static string Clearing_Thumbnail_Cache {
            get {
                return ResourceManager.GetString("Clearing_Thumbnail_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t Connect!
        ///¡No se pudo conectar!.
        /// </summary>
        internal static string Couldn_t_Connect {
            get {
                return ResourceManager.GetString("Couldn_t_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo conectar para recibir actualizaciones. Es posible que su conexión no funcione, que esté comprobando con demasiada frecuencia o que Github no funcione. ¿Intentar comprobar de nuevo más tarde?.
        /// </summary>
        internal static string Couldn_t_connect_to_get_updates__Your_connection_might_be_down__you_re_checking_too_often__or_Github_is_down__Try_checking_again_later {
            get {
                return ResourceManager.GetString("Couldn_t_connect_to_get_updates__Your_connection_might_be_down__you_re_checking_t" +
                        "oo_often__or_Github_is_down__Try_checking_again_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo borrar .
        /// </summary>
        internal static string Couldn_t_delete {
            get {
                return ResourceManager.GetString("Couldn_t_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo eliminar .
        /// </summary>
        internal static string Couldn_t_remove {
            get {
                return ResourceManager.GetString("Couldn_t_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creado por Thomas Loupe..
        /// </summary>
        internal static string Created_by_Thomas_Loupe {
            get {
                return ResourceManager.GetString("Created_by_Thomas_Loupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminado: .
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorio ya eliminado: .
        /// </summary>
        internal static string Directory_already_removed {
            get {
                return ResourceManager.GetString("Directory_already_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se borró la caché perimetral..
        /// </summary>
        internal static string Edge_Cache_Was_Cleared {
            get {
                return ResourceManager.GetString("Edge_Cache_Was_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge de datos de borde: .
        /// </summary>
        internal static string Edge_Data_Size {
            get {
                return ResourceManager.GetString("Edge_Data_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Papelera de reciclaje vacía.
        ///
        ///.
        /// </summary>
        internal static string Emptied_Recycle_Bin {
            get {
                return ResourceManager.GetString("Emptied_Recycle_Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaciar la papelera de reciclaje.
        /// </summary>
        internal static string Emptying_Recycle_Bin {
            get {
                return ResourceManager.GetString("Emptying_Recycle_Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar cualquier proceso de Chrome.
        /// </summary>
        internal static string Ending_any_Chrome_processes {
            get {
                return ResourceManager.GetString("Ending_any_Chrome_processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalización de cualquier proceso de Edge.
        /// </summary>
        internal static string Ending_any_Edge_processes {
            get {
                return ResourceManager.GetString("Ending_any_Edge_processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se borraron los registros de eventos..
        /// </summary>
        internal static string Event_Logs_Were_Cleared {
            get {
                return ResourceManager.GetString("Event_Logs_Were_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se encontró la caché de Windows Installer. Limpieza.
        /// </summary>
        internal static string Found_Windows_Installer_Cache_Cleaning {
            get {
                return ResourceManager.GetString("Found_Windows_Installer_Cache_Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se encontró el directorio Windows.old. Limpieza.
        /// </summary>
        internal static string Found_Windows_Old_Directory_Cleaning {
            get {
                return ResourceManager.GetString("Found_Windows_Old_Directory_Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github: https://github.com/thomasloupe.
        /// </summary>
        internal static string Github__https___github_com_thomasloupe {
            get {
                return ResourceManager.GetString("Github__https___github_com_thomasloupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Si se habilitó el historial de archivos, se eliminaron todas las versiones excepto la última.
        ///
        ///
        ///.
        /// </summary>
        internal static string If_File_History_Was_Enabled_All_Versions_Except_The_Latest_Were_Removed {
            get {
                return ResourceManager.GetString("If_File_History_Was_Enabled_All_Versions_Except_The_Latest_Were_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB de eliminar la caché de MSO..
        /// </summary>
        internal static string MB_from_removing_MSO_Cache {
            get {
                return ResourceManager.GetString("MB_from_removing_MSO_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB de eliminar archivos temporales..
        /// </summary>
        internal static string MB_from_removing_Temporary_Files {
            get {
                return ResourceManager.GetString("MB_from_removing_Temporary_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB de eliminar archivos temporales de Internet..
        /// </summary>
        internal static string MB_from_removing_Temporary_Internet_Files {
            get {
                return ResourceManager.GetString("MB_from_removing_Temporary_Internet_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB de eliminar archivos temporales de instalación..
        /// </summary>
        internal static string MB_from_removing_Temporary_Setup_Files {
            get {
                return ResourceManager.GetString("MB_from_removing_Temporary_Setup_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB 
        ///de eliminar archivos de optimización de entrega de Windows..
        /// </summary>
        internal static string MB_from_removing_Windows_Delivery_Optimization_Files {
            get {
                return ResourceManager.GetString("MB_from_removing_Windows_Delivery_Optimization_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB de eliminar los informes de errores de Windows..
        /// </summary>
        internal static string MB_from_removing_Windows_Error_Reports_ {
            get {
                return ResourceManager.GetString("MB_from_removing_Windows_Error_Reports_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB de eliminar la caché de Windows Installer..
        /// </summary>
        internal static string MB_from_removing_Windows_Installer_Cache {
            get {
                return ResourceManager.GetString("MB_from_removing_Windows_Installer_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB de eliminar los registros de actualización de Windows..
        /// </summary>
        internal static string MB_from_removing_Windows_Update_Logs {
            get {
                return ResourceManager.GetString("MB_from_removing_Windows_Update_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSO Tamaño del caché: .
        /// </summary>
        internal static string MSO_Cache_size {
            get {
                return ResourceManager.GetString("MSO_Cache_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es necesario limpiar los archivos de optimización de entrega.
        ///
        ///.
        /// </summary>
        internal static string No_Delivery_Optimization_Files_Needed_To_Be_Cleaned {
            get {
                return ResourceManager.GetString("No_Delivery_Optimization_Files_Needed_To_Be_Cleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///No se encontró el directorio MSOCache. Salto a la comba...
        ///
        ///.
        /// </summary>
        internal static string No_MSO_Cache_Directory_Found_Skipping {
            get {
                return ResourceManager.GetString("No_MSO_Cache_Directory_Found_Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///No se encontró el directorio Windows.old. Salto a la comba...
        ///
        ///.
        /// </summary>
        internal static string No_Windows_Old_Directory_Found {
            get {
                return ResourceManager.GetString("No_Windows_Old_Directory_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///No se encontró el directorio de registros de Windows Update. Salto a la comba...
        ///
        ///.
        /// </summary>
        internal static string No_Windows_Update_Logs_Directory_Found_Skipping {
            get {
                return ResourceManager.GetString("No_Windows_Update_Logs_Directory_Found_Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Se eliminaron las versiones antiguas de Windows..
        /// </summary>
        internal static string Old_Versions_Of_Windows_Were_Removed {
            get {
                return ResourceManager.GetString("Old_Versions_Of_Windows_Were_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espacio potencial para recuperar: .
        /// </summary>
        internal static string Potential_space_to_reclaim {
            get {
                return ResourceManager.GetString("Potential_space_to_reclaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperado .
        /// </summary>
        internal static string Recovered {
            get {
                return ResourceManager.GetString("Recovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados de recuperación:.
        /// </summary>
        internal static string Recovery_Results {
            get {
                return ResourceManager.GetString("Recovery_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///La papelera de reciclaje se vació..
        /// </summary>
        internal static string Recycle_Bin_Was_Emptied {
            get {
                return ResourceManager.GetString("Recycle_Bin_Was_Emptied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoto.
        /// </summary>
        internal static string Removed_ {
            get {
                return ResourceManager.GetString("Removed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoto: .
        /// </summary>
        internal static string Removed__ {
            get {
                return ResourceManager.GetString("Removed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Se eliminó el historial de archivos anterior a la última instantánea..
        /// </summary>
        internal static string Removed_File_History_Older_Than_Latest_Snapshot {
            get {
                return ResourceManager.GetString("Removed_File_History_Older_Than_Latest_Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando versiones antiguas de Windows.
        /// </summary>
        internal static string Removing_old_versions_of_Windows {
            get {
                return ResourceManager.GetString("Removing_old_versions_of_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar la caché de Windows Installer.
        /// </summary>
        internal static string Removing_Windows_Installer_Cache {
            get {
                return ResourceManager.GetString("Removing_Windows_Installer_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Se reinició el proceso Explorer.exe..
        /// </summary>
        internal static string Restarted_Explorer_exe_Process {
            get {
                return ResourceManager.GetString("Restarted_Explorer.exe_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Cerrar el proceso Explorer.exe....
        /// </summary>
        internal static string Shutting_Down_Explorer_exe_Process {
            get {
                return ResourceManager.GetString("Shutting_Down_Explorer.exe_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Salto a la comba....
        /// </summary>
        internal static string Skipping {
            get {
                return ResourceManager.GetString("Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salto a la comba....
        /// </summary>
        internal static string Skipping_ {
            get {
                return ResourceManager.GetString("Skipping_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salto a la comba: .
        /// </summary>
        internal static string Skipping__ {
            get {
                return ResourceManager.GetString("Skipping__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Salto a la comba....
        /// </summary>
        internal static string Skipping___ {
            get {
                return ResourceManager.GetString("Skipping___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Procesos de Chrome detenidos.
        ///.
        /// </summary>
        internal static string Stopped_Chrome_Processes {
            get {
                return ResourceManager.GetString("Stopped_Chrome_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Procesos de Edge detenidos.
        ///.
        /// </summary>
        internal static string Stopped_Edge_Processes {
            get {
                return ResourceManager.GetString("Stopped_Edge_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barriendo la caché de Chrome...
        ///.
        /// </summary>
        internal static string Sweeping_Chrome_Cache {
            get {
                return ResourceManager.GetString("Sweeping_Chrome_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrido de archivos de optimización de entrega...
        ///.
        /// </summary>
        internal static string Sweeping_Delivery_Information_Files {
            get {
                return ResourceManager.GetString("Sweeping_Delivery_Information_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrido de caché de Edge...
        ///.
        /// </summary>
        internal static string Sweeping_Edge_Cache {
            get {
                return ResourceManager.GetString("Sweeping_Edge_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrido de registros del visor de eventos.
        /// </summary>
        internal static string Sweeping_Event_Viewer_Logs {
            get {
                return ResourceManager.GetString("Sweeping_Event_Viewer_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrido de caché de MSO.
        /// </summary>
        internal static string Sweeping_MSO_cache {
            get {
                return ResourceManager.GetString("Sweeping_MSO_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrido de archivos temporales de Internet...
        ///.
        /// </summary>
        internal static string Sweeping_Temporary_Files {
            get {
                return ResourceManager.GetString("Sweeping_Temporary_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweeping Temporary Internet Files...
        ///.
        /// </summary>
        internal static string Sweeping_Temporary_Internet_Files {
            get {
                return ResourceManager.GetString("Sweeping_Temporary_Internet_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrido de archivos de configuración temporal...
        ///.
        /// </summary>
        internal static string Sweeping_Temporary_Setup_Files {
            get {
                return ResourceManager.GetString("Sweeping_Temporary_Setup_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrido de archivos de registro de Windows Defender...
        ///.
        /// </summary>
        internal static string Sweeping_Windows_Defender_Log_Files {
            get {
                return ResourceManager.GetString("Sweeping_Windows_Defender_Log_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informes de errores de barrido de Windows
        ///.
        /// </summary>
        internal static string Sweeping_Windows_Error_Reports {
            get {
                return ResourceManager.GetString("Sweeping_Windows_Error_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrido de registros de actualización de Windows
        ///.
        /// </summary>
        internal static string Sweeping_Windows_Update_Logs {
            get {
                return ResourceManager.GetString("Sweeping_Windows_Update_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Caché de Chrome barrido!
        ///
        ///.
        /// </summary>
        internal static string Swept_Chrome_Cache {
            get {
                return ResourceManager.GetString("Swept_Chrome_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Archivos de optimización de envío barrido!
        ///
        ///.
        /// </summary>
        internal static string Swept_Delivery_Optimization_Files {
            get {
                return ResourceManager.GetString("Swept_Delivery_Optimization_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Caché de Edge barrido!
        ///
        ///.
        /// </summary>
        internal static string Swept_Edge_Cache {
            get {
                return ResourceManager.GetString("Swept_Edge_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///¡Registros barridos del visor de eventos!
        ///
        ///.
        /// </summary>
        internal static string Swept_Event_Viewer_Logs {
            get {
                return ResourceManager.GetString("Swept_Event_Viewer_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///¡Barrió el caché de MSO!
        ///
        ///.
        /// </summary>
        internal static string Swept_MSO_Cache {
            get {
                return ResourceManager.GetString("Swept_MSO_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Archivos temporales barridos!
        ///
        ///.
        /// </summary>
        internal static string Swept_Temporary_Files {
            get {
                return ResourceManager.GetString("Swept_Temporary_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///¡Barrió archivos temporales de Internet!
        ///
        ///.
        /// </summary>
        internal static string Swept_Temporary_Internet_Files {
            get {
                return ResourceManager.GetString("Swept_Temporary_Internet_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///¡Archivos de configuración temporales barridos!
        ///
        ///.
        /// </summary>
        internal static string Swept_Temporary_Setup_Files {
            get {
                return ResourceManager.GetString("Swept_Temporary_Setup_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///¡Caché de miniaturas barridas!
        ///
        ///.
        /// </summary>
        internal static string Swept_Thumbnail_Cache {
            get {
                return ResourceManager.GetString("Swept_Thumbnail_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Informes de errores de Windows barridos!
        ///
        ///.
        /// </summary>
        internal static string Swept_Windows_Error_Reports {
            get {
                return ResourceManager.GetString("Swept_Windows_Error_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///¡Barrió la caché del instalador de Windows!
        ///
        ///.
        /// </summary>
        internal static string Swept_Windows_Installer_Cache {
            get {
                return ResourceManager.GetString("Swept_Windows_Installer_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///¡Barrió el directorio Windows.old!
        ///
        ///.
        /// </summary>
        internal static string Swept_Windows_Old_Directory {
            get {
                return ResourceManager.GetString("Swept_Windows_Old_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///¡Barrió los registros de actualización de Windows!
        ///
        ///.
        /// </summary>
        internal static string Swept_Windows_Update_Logs {
            get {
                return ResourceManager.GetString("Swept_Windows_Update_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño del directorio temporal: .
        /// </summary>
        internal static string Temp_Directory_size {
            get {
                return ResourceManager.GetString("Temp_Directory_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño del directorio de archivos temporales de Internet: .
        /// </summary>
        internal static string Temporary_Internet_Files_directory_size {
            get {
                return ResourceManager.GetString("Temporary_Internet_Files_directory_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño del directorio de archivos de configuración temporal: .
        /// </summary>
        internal static string Temporary_Setup_Files_directory_size {
            get {
                return ResourceManager.GetString("Temporary_Setup_Files_directory_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se borró la caché de miniaturas..
        /// </summary>
        internal static string Thumbnail_Cache_Was_Cleared {
            get {
                return ResourceManager.GetString("Thumbnail_Cache_Was_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Espacio total recuperado: .
        /// </summary>
        internal static string Total_Space_Recovered {
            get {
                return ResourceManager.GetString("Total_Space_Recovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Espacio total recuperado: &lt;1MB
        ///.
        /// </summary>
        internal static string Total_Space_Recovered__1MB {
            get {
                return ResourceManager.GetString("Total_Space_Recovered_<1MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter: https://twitter.com/acid_rain.
        /// </summary>
        internal static string Twitter__https___twitter_com_acid_rain {
            get {
                return ResourceManager.GetString("Twitter__https___twitter_com_acid_rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Actualización disponible!.
        /// </summary>
        internal static string Update_Available {
            get {
                return ResourceManager.GetString("Update_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitio web: https://thomasloupe.com.
        /// </summary>
        internal static string Website__https___thomasloupe_com {
            get {
                return ResourceManager.GetString("Website__https___thomasloupe_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se eliminaron los registros de Windows Defender..
        /// </summary>
        internal static string Windows_Defender_Logs_Were_Removed {
            get {
                return ResourceManager.GetString("Windows_Defender_Logs_Were_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimización de entrega de Windows Tamaño de archivo: .
        /// </summary>
        internal static string Windows_Delivery_Optimization_File_size {
            get {
                return ResourceManager.GetString("Windows_Delivery_Optimization_File_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El directorio de informe de errores de Windows ya se eliminó. Salto a la comba
        ///
        ///.
        /// </summary>
        internal static string Windows_Error_Report_Directory_Already_Removed_Skipping {
            get {
                return ResourceManager.GetString("Windows_Error_Report_Directory_Already_Removed_Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño de los informes de error de Windows: .
        /// </summary>
        internal static string Windows_Error_Reports_size {
            get {
                return ResourceManager.GetString("Windows_Error_Reports_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño de la caché de Windows Installer: .
        /// </summary>
        internal static string Windows_Installer_Cache_size {
            get {
                return ResourceManager.GetString("Windows_Installer_Cache_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño de los registros de Windows Update: .
        /// </summary>
        internal static string Windows_Update_Logs_size {
            get {
                return ResourceManager.GetString("Windows_Update_Logs_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Le gustaría visitar la página de descarga?.
        /// </summary>
        internal static string Would_you_like_to_visit_the_download_page_ {
            get {
                return ResourceManager.GetString("Would_you_like_to_visit_the_download_page_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienes la última versión, .
        /// </summary>
        internal static string You_have_the_latest_version {
            get {
                return ResourceManager.GetString("You_have_the_latest_version", resourceCulture);
            }
        }
    }
}
